ktor:
  host: 127.0.0.1
  port: 8080
api:
  gemini:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
    key: # Your API key here
  weather:
    url: https://api.weatherapi.com/v1
    key: # Your API key here
